### ISSUE TITLE
react-native run-ios 出错

### ISSUE THREAD

**Issue by hejunbinlan** [nickming/ReactWeather#2]
Loading dependency graph, done.
error: bundling: NotFoundError: Cannot find entry file index.ios.js in any of the roots: ["/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_react-native@0.44.0@react-native","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_absolute-path@0.0.0@absolute-path","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_art@0.10.1@art","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_async@2.4.1@async","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-core@6.24.1@babel-core","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-generator@6.24.1@babel-generator","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-plugin-external-helpers@6.22.0@babel-plugin-external-helpers","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-plugin-syntax-trailing-function-commas@6.22.0@babel-plugin-syntax-trailing-function-commas","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-plugin-transform-async-to-generator@6.16.0@babel-plugin-transform-async-to-generator","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-plugin-transform-flow-strip-types@6.22.0@babel-plugin-transform-flow-strip-types","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-plugin-transform-object-rest-spread@6.23.0@babel-plugin-transform-object-rest-spread","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-polyfill@6.23.0@babel-polyfill","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-preset-es2015-node@6.1.1@babel-preset-es2015-node","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-preset-fbjs@2.1.2@babel-preset-fbjs","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-preset-react-native@1.9.2@babel-preset-react-native","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-register@6.24.1@babel-register","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-runtime@6.23.0@babel-runtime","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-traverse@6.24.1@babel-traverse","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babel-types@6.24.1@babel-types","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_babylon@6.17.2@babylon","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_base64-js@1.2.0@base64-js","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_bser@1.0.3@bser","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_chalk@1.1.3@chalk","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_commander@2.9.0@commander","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_concat-stream@1.6.0@concat-stream","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_connect@2.30.2@connect","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_core-js@2.4.1@core-js","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_debug@2.6.8@debug","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_denodeify@1.2.1@denodeify","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_event-target-shim@1.1.1@event-target-shim","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_fbjs@0.8.12@fbjs","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_fbjs-scripts@0.7.1@fbjs-scripts","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_form-data@2.1.4@form-data","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_fs-extra@1.0.0@fs-extra","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_glob@7.1.2@glob","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_graceful-fs@4.1.11@graceful-fs","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_image-size@0.3.5@image-size","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_immutable@3.7.6@immutable","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_imurmurhash@0.1.4@imurmurhash","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_inquirer@0.12.0@inquirer","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_jest-haste-map@19.0.0@jest-haste-map","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_joi@6.10.1@joi","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_json-stable-stringify@1.0.1@json-stable-stringify","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_json5@0.4.0@json5","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_left-pad@1.1.3@left-pad","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_lodash@4.17.4@lodash","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_mime@1.3.6@mime","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_mime-types@2.1.11@mime-types","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_minimist@1.2.0@minimist","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_mkdirp@0.5.1@mkdirp","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_node-fetch@1.7.1@node-fetch","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_npmlog@2.0.4@npmlog","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_opn@3.0.3@opn","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_optimist@0.6.1@optimist","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_plist@1.2.0@plist","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_pretty-format@4.3.1@pretty-format","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_promise@7.1.1@promise","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_react-clone-referenced-element@1.0.1@react-clone-referenced-element","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_react-devtools-core@2.3.0@react-devtools-core","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_react-timer-mixin@0.13.3@react-timer-mixin","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_react-transform-hmr@1.0.4@react-transform-hmr","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_rebound@0.0.13@rebound","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_regenerator-runtime@0.9.6@regenerator-runtime","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_request@2.81.0@request","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_rimraf@2.6.1@rimraf","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_sane@1.4.1@sane","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_semver@5.3.0@semver","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_shell-quote@1.6.1@shell-quote","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_source-map@0.5.6@source-map","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_stacktrace-parser@0.1.4@stacktrace-parser","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_temp@0.8.3@temp","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_throat@3.1.0@throat","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_uglify-js@2.7.5@uglify-js","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_whatwg-fetch@1.1.1@whatwg-fetch","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_wordwrap@1.0.0@wordwrap","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_worker-farm@1.3.1@worker-farm","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_write-file-atomic@1.3.4@write-file-atomic","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_ws@1.1.4@ws","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_xcode@0.9.3@xcode","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_xmldoc@0.4.0@xmldoc","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_xpipe@1.0.5@xpipe","/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_yargs@6.6.0@yargs"]
    at DependencyGraph._getAbsolutePath (/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_react-native@0.44.0@react-native/packager/src/node-haste/index.js:272:11)
    at DependencyGraph.getDependencies (/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_react-native@0.44.0@react-native/packager/src/node-haste/index.js:216:26)
    at Resolver.getDependencies (/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_react-native@0.44.0@react-native/packager/src/Resolver/index.js:106:27)
    at _resolverPromise.then.resolver (/Users/admin/workspace-js/ReactNative/openproject/ReactWeather-master/node_modules/_react-native@0.44.0@react-native/packager/src/Bundler/index.js:561:62)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Bundling `index.ios.js`  0.0% (0/1), failed.

**Comment by nickming** [comment]
是不是没有clone完整或者没有npm install?
